FyBlog/FyBlog/FyBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps import views as sitemap_views
from django.conf import settings
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
from django.conf.urls.static import static
from blog.views import *
import blog.urls
from blog.views import index
import login.urls
import user.urls
import comment.urls
from django.views.static import serve
from FyBlog.settings import MEDIA_ROOT

urlpatterns = [
    path('',index,name='index_site'),
    path('admin/', admin.site.urls),
    path('blog/',include(blog.urls)),
    path('login/',include(login.urls)),
    path('user/',include(user.urls)),
    path('mdeditor/', include('mdeditor.urls')),
    path('media/', serve, {"document_root": MEDIA_ROOT}),
    path('comment/',include(comment.urls)),
    path('rss/',LatestPostFeed(),name = 'rss'),
    path('sitemap.xml/',sitemap_views.sitemap,{'sitemaps':{'posts':PostSitemap}},name='sitemap'),
]
if settings.DEBUG:
    # statikc files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FyBlog/FyBlog/blog/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps import views as sitemap_views
from blog.views import *
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap

urlpatterns = [
   path('index/',IndexView.as_view(),name="index"),
   path('post_detail/<int:post_id>',PostView.as_view(),name='post_detail'),
   path('category/<int:category_id>',CategoryView.as_view(),name='category'),
   path('achieved/',AchieveViews.as_view(),name="achieved"),
   re_path(r'tag/$',TagView.as_view(),name='tag'),
   re_path(r'^search/$',SearchView.as_view(),name='search'),

]

FyBlog/FyBlog/login/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
import login.views as views
import forget_password.urls


urlpatterns = [
    path('',views.login.as_view(),name = "login"),
    re_path(r'register_status/$',views.type_judge.as_view(),name='register_status'),
    path('register/',views.type_judge.as_view(),name='register'),
    path('logout/',views.logout,name="logout"),
    path("forget_password/",include(forget_password.urls)),


]

FyBlog/FyBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps import views as sitemap_views
from django.conf import settings
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
from django.conf.urls.static import static
from blog.views import *
import blog.urls
from blog.views import index
import login.urls
import user.urls
import comment.urls
from django.views.static import serve
from FyBlog.settings import MEDIA_ROOT

urlpatterns = [
    path('',index,name='index_site'),
    path('admin/', admin.site.urls),
    path('blog/',include(blog.urls)),
    path('login/',include(login.urls)),
    path('user/',include(user.urls)),
    path('mdeditor/', include('mdeditor.urls')),
    path('media/', serve, {"document_root": MEDIA_ROOT}),
    path('comment/',include(comment.urls)),
    path('rss/',LatestPostFeed(),name = 'rss'),
    path('sitemap.xml/',sitemap_views.sitemap,{'sitemaps':{'posts':PostSitemap}}),
]
if settings.DEBUG:
    # statikc files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FyBlog/FyBlog/blog/models.py
from django.db import models
from django.utils.html import mark_safe
from markdown import markdown
from django.contrib.auth.models import User
from mdeditor.fields import MDTextField
from django.utils.html import format_html
import time

# Create your models here.

class Category(models.Model):
    STATUS_NORMAL = 0  # 正常
    STATUS_DELETE = 1  # 删除
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    name = models.CharField(max_length=255,verbose_name='分类名称')
    owner = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='分类作者')
    status = models.PositiveIntegerField(verbose_name='状态',default=STATUS_NORMAL,choices=STATUS_ITEMS)
    is_nav = models.BooleanField(default=False,verbose_name='是否为导航')
    created_time = models.DateTimeField(verbose_name='分类创建时间',auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_plural = "分类"


    @classmethod
    def get_all(cls):
        return cls.objects.filter(status=cls.STATUS_NORMAL)

class Tag(models.Model):
    STATUS_NORMAL = 0  # 正常
    STATUS_DELETE = 1  # 删除
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    name = models.CharField(verbose_name='标签名称',max_length=255)
    status = models.PositiveIntegerField(default=STATUS_NORMAL,choices=STATUS_ITEMS,verbose_name='状态')
    owner = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='标签作者')
    created_time = models.DateTimeField(verbose_name='标签创建时间',auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_plural = '标签'


class Post(models.Model):
    STATUS_NORMAL = 0  #正常
    STATUS_DELETE = 1  #删除
    STATUS_DRAFT = 2 #草稿
    STATUS_ITEMS =(
        (STATUS_NORMAL,'正常'),
        (STATUS_DELETE,'删除'),
        (STATUS_DRAFT,'草稿')
    )
    title = models.CharField(verbose_name='标题',max_length=255)
    desc = models.TextField(verbose_name='摘要', help_text='关于文章的简单描述')
    status = models.PositiveIntegerField(verbose_name='状态',default=STATUS_NORMAL,choices=STATUS_ITEMS)
    content = MDTextField(verbose_name='正文', help_text='正文必须是markdown格式')
    content_html = models.TextField(verbose_name='正文html代码', blank=True, editable=False)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name='分类')
    tag = models.ManyToManyField(Tag,verbose_name='标签')
    owner = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='作者')
    created_time = models.DateTimeField(auto_now_add=True,verbose_name='文章创建时间')
    updated_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")
    uv = models.PositiveIntegerField(default=1)
    pv = models.PositiveIntegerField(default=1)


    class Meta:
        verbose_name = verbose_name_plural = '文章'

    def __str__(self):
        return self.title

    @classmethod
    def count(self):
        return self.objects.count()

    @classmethod
    def latest_posts(cls):
        queryset = cls.objects.filter(status=cls.STATUS_NORMAL)
        return queryset

    @classmethod
    def get_category(cls,id):
         queryset = cls.objects.filter(status=cls.STATUS_NORMAL).filter(category_id=id)
         return queryset


    def color_status(self):
        if self.status == self.STATUS_NORMAL:
            color = 'green'
        elif self.status == self.STATUS_DRAFT:
            color = 'brown'
        else:
            color = 'red'
        return format_html(
            '<span style="color:{}">{}</span>',
                color,
                self.STATUS_ITEMS[self.status][1]

        )

    color_status.short_description = "状态"

FyBlog/FyBlog/login/forms.py
from django import forms
from django.forms import widgets
from blog.models import Category
from login.models import User

import re
import string

class RegisterForm(forms.Form):
    QUESTIONS_1 = 0
    QUESTIONS_2 = 1
    QUESTIONS_3 = 2
    QUESTIONS_4 = 3
    QUESTIONS_5 = 4

    Questions = (
        (QUESTIONS_1, "你的第一辆车？"),
        (QUESTIONS_2, "你初中学校的名字？"),
        (QUESTIONS_3, "你父亲的生日？"),
        (QUESTIONS_4, "你母亲的生日？"),
        (QUESTIONS_5, "你宠物的名字？")
    )

    nick = forms.CharField(label="昵称",widget=widgets.TextInput(attrs={'class':'input'}))
    Email = forms.EmailField(required=True,label="邮箱",error_messages={'required': '该字段不能为空',"invalid":"请输入正确的emil格式！"},
                             widget = widgets.TextInput(attrs={'class':"input"}))
    password = forms.CharField(required=True,label="密码",max_length=20,min_length=6,error_messages={'required': '密码不能为空',
                                                                                                  'max_length':'密码长度最少为20位',
                                                                                                  'min_length':"密码长度最少为6位"},
                               widget = widgets.PasswordInput(attrs={'class':"input"}),help_text="不少于20字符")
    re_password = forms.CharField(label="确认密码",max_length=20,error_messages={'requried': '两次输入的密码不一致！'},
                                  widget = widgets.PasswordInput(attrs={"class":"input"}))
    question1 = forms.IntegerField(widget=widgets.Select(choices=Questions,attrs={'class':'select'}),label="密保问题1",)
    answer1 = forms.CharField(label="答案",widget=widgets.TextInput(attrs={'class':'input'}))
    question2 = forms.IntegerField(widget=widgets.Select(choices=Questions, attrs={'class': 'select'}), label="密保问题2", )
    answer2 = forms.CharField(label="答案", widget=widgets.TextInput(attrs={'class': 'input'}))

    class Meta:
        model = User


    def clean_nick(self):
        cd = self.cleaned_data
        user = User.objects.filter(status=User.STATUS_NORMAL)
        for obj in user:
            if obj == None:
                break
            if cd['nick'] == obj.nick:
                raise forms.ValidationError('该昵称已被注册')
            else:
                pass

        return cd['nick']

    def clean_password(self):
        cd = self.cleaned_data
        num = [x for x in string.digits]
        letter = [x for x in string.ascii_letters]
        number_count = 0
        letter_count = 0
        for i in cd['password']:
            if i in num :
                number_count += 1
            if i in letter:
                letter_count += 1

        if number_count == 0 or letter_count == 0:
            raise forms.ValidationError("密码中必须包含英文和数字！")
        else:
            return cd['password']

    def clean_re_password(self):
        cd = self.cleaned_data
        try:
            if cd['re_password'] != cd["password"]:
                raise forms.ValidationError("两次密码不一致！")
            else:
                return cd['re_password']
        except KeyError:
            raise forms.ValidationError("两次密码不一致！")


    def clean_question2(self):
        cd = self.cleaned_data
        if cd['question2'] == cd['question1']:
            raise forms.ValidationError("两次问题不能相同！")
        else:
            return cd['question2']


    def clean_Email(self):
        cd = self.cleaned_data
        user = User.objects.filter(status=User.STATUS_NORMAL)
        for obj in user:
            if obj == None:
                break
            if cd['Email'] == obj.username:
                raise forms.ValidationError('该邮箱已被注册')
            else:
                pass

        return cd['Email']


class LoginForm(forms.Form):
    STATUS_ITEM = (
        (0,'不记住'),
        (1,'记住我')
    )

    Email = forms.EmailField(required=True, label="邮箱",
                             error_messages={'required': '该字段不能为空', "invalid": "请输入正确的emil格式！"},
                             widget=widgets.TextInput(attrs={'class': "input"}))
    password = forms.CharField(required=True, label="密码", max_length=20, min_length=6,
                               error_messages={'required': '密码不能为空',
                                               'max_length': '密码长度最少为20位',
                                               'min_length': "密码长度最少为6位"},
                               widget=widgets.PasswordInput(attrs={'class': "input"}), help_text="不少于20字符")
    remember = forms.CharField(required=False,widget=widgets.CheckboxInput,label='记住我')

    class Meta:
        meodel = User




    def clean_password(self):
        cd = self.cleaned_data
        if 'Email' in cd.keys():
            username = cd['Email']
            user = User.objects.filter(status=User.STATUS_NORMAL)
            for obj in user:
                if username == obj.username:
                    return cd['password']
                else:
                    pass

            raise forms.ValidationError('邮箱或者密码错误！')

FyBlog/FyBlog/blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.db.models import Q,F
from django.core.cache import cache
from django.views import View
from django.views.generic import DetailView,ListView
from blog.models import Post,Tag,Category
from config.models import SideBar,VisitNumber,Link
from comment.models import Comment
from login.views import hash_md5
from login.models import User
from datetime import date
from config.visit_info import change_info
import markdown

import time
# Create your views here.



from django.shortcuts import HttpResponse,Http404

#跳转到主页
def index(request):
    return redirect('index')


class CommonView:
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        url = self.request.path
        visit_num = VisitNumber.objects.get(id=1)
        usernm_md5 = self.request.session.get('username')
        if usernm_md5:
            user = User.latest_posts()
            for obj in user:
                if hash_md5(obj.username) == usernm_md5:
                    context.update({
                        "user": obj
                    })
        context.update({
            'Sidebar': SideBar.get_all(),
            'count':Post.count(),
            "links":Link.get_all(),
            'comment':Comment.count(),
            'category':Category.get_all(),
            'url':url,
            "visit_num":visit_num.count
        })
        return context


class IndexView(CommonView,ListView):
    queryset = Post.latest_posts().order_by('id')
    context_object_name = 'post'
    paginate_by = 5
    template_name = 'blog/list.html'


    def get(self,request,*args,**kwargs):
        change_info(request)
        response = super().get(request,*args,**kwargs)
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.session.get("is_login",None):
            login_sidebar = SideBar.objects.get(pk=5)
            login_sidebar.status = 0
            login_sidebar.save()

        return context

class PostView(CommonView,DetailView):
    queryset = Post.latest_posts()
    context_object_name = 'post'
    pk_url_kwarg = 'post_id'
    template_name = 'blog/post_detail.html'

    def get(self,request,*args,**kwargs):
        response = super().get(request, *args,**kwargs)
        self.hanle_visited()
        return response

    def hanle_visited(self):
        increase_pv = False
        increase_uv = False
        uid = self.request.uid
        pv_key = "pv:%s:%s"%(uid,self.request.path)
        uv_key = "uv:%s:%s:%s" % (uid, str(date.today()),self.request.path)
        if not cache.get(pv_key):
            increase_pv = True
            cache.set(pv_key,1,1*60)

        if not cache.get(uv_key):
            increase_uv = True
            cache.set(pv_key,1,24*60*60)

        if increase_pv and increase_uv:
            Post.objects.filter(pk=self.object.id).update(pv=F('pv')+1,uv=F('uv')+1)
        elif increase_pv:
            Post.objects.filter(pk=self.object.id).update(pv=F('pv') + 1)
        elif increase_pv:
            Post.objects.filter(pk=self.object.id).update(pv=F('uv') + 1)


    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        post_id = self.kwargs.get('post_id')
        queryset_created = str(Post.objects.get(pk = post_id).created_time).split(" ")[0]
        queryset_updated = str(Post.objects.get(pk = post_id).updated_time).split(" ")[0]
        uv = Post.objects.get(pk=post_id).uv
        if self.request.session.get("is_login",None):
            login_sidebar = SideBar.objects.get(pk=5)
            login_sidebar.status = 0
            login_sidebar.save()
        context.update({
            "Created_time":queryset_created,
            "Updated_time":queryset_updated,
            "uv":uv
        })
        return context





class CategoryView(IndexView):
    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id = category_id)

class TagView(IndexView):
    def get_queryset(self):
        queryset = super().get_queryset()
        tag_id = self.request.GET.get('tag')
        return queryset.filter(tag__id = tag_id)


class SearchView(IndexView):
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        keyword = self.request.GET.get('keyword')
        context.update({
            'fail_message':'本次查询到0个结果!',
            'success_message':"本次关于'{}'查询到{}个结果！".format(keyword,self.get_queryset().count())
        })
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        keyword = self.request.GET.get('keyword')
        return queryset.filter(Q(title__icontains=keyword)|Q(desc__icontains=keyword))


class AchieveViews(IndexView):
    queryset = Post.latest_posts().order_by('-created_time')
    context_object_name = 'post'
    paginate_by = 10
    template_name = "blog/file.html"

FyBlog/FyBlog/FyBlog/theme/bootstrap/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <title>{% block title %}首页{% endblock %}  FyBlog's 博客系统</title>
    <link href="{% static 'css/bulma.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/user.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdeditor.css' %}" rel="stylesheet">
    <link rel="stylesheet" href={% static 'css/prettify.css' %} /> <!-- 设置代码主题，此文件为默认主题，可以换成其他主题-->
    <script src="{% static 'js/query.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/prettify.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/load.js' %}" type="text/javascript"></script>
    {% block head %}

    {% endblock %}
</head>

<body onload="prettyPrint()">
    <div id="home">
        {# 页头 #}
        <div id="head">
            <div class="level">
                <div class="level_left">
                    <div id="blog_title" style="display: none">
                        <h1><a id="MainTitle" href="{% url 'index' %}">Geralt</a></h1>
                        <h2>个人简介：https://github.com/fengyuakmeng | 不定时更新</h2>
                    </div>
                </div>
            </div>
            <div id="blog_category" >
                <hr>
                <nav class="level">
                    <div class="level-left">
                        <nav class="breadcrumb" aria-label="breadcrumbs" style="display: none">
                            <ul>
                                <li><a href="{% url 'index' %}"><span class="icon is-small"><i class="fa fa-home"></i></span>主页</a></li>
                                {% for foo in category %}
                                    {% if foo.is_nav == 1 %}
                                        <li><a href="{% url 'category' foo.id %}">{{ foo.name }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                <li><a href="{% url 'achieved' %}">归档</a></li>


                            </ul>
                        </nav>
                    </div>
                    <div class="level-right">
                        <span>文章：{{ count }}</span>&nbsp;
                        <span>评论：{{ comment }}</span>&nbsp;
                        <span>访问量：{{ visit_num }}</span>&nbsp;
                    </div>
                </nav>
                <hr/>
            </div>
        </div>
        <div id="main">
            <div class="Content">
                {% block content %}{% endblock %}
                <br>
                {% block comment %}{% endblock %}
{#            {% if page_obj %}#}
{#                {% if page_obj.has_previous %}#}
{#                    <a href="?page={{ page_boj.previous_page_number }}">上一页</a>#}
{#                {% endif %}#}
{#                Page {{ page_obj.number }} of {{ paginator.num_pages }}#}
{#                {% if page_obj.has_next %}#}
{#                    <a href="?page={{ page_boj.next_page_number }}">下一页</a>#}
{#                {% endif %}#}
{#            {% endif %}#}
            {% if page_obj %}
            <nav class="pagination post_card" role="navigation" aria-label="pagination">
                {% if page_obj.has_previous %}
                <a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    {% endif %}
                {% if page_obj.has_next %}
                <a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
                    {% endif %}
                <ul class="pagination-list">
                    {% for page in paginator.page_range %}
                        {% if page_obj.number == page %}
                            <li><a class="pagination-link is-active" aria-label="Goto page 1" href="?page={{ page }}">{{ page }}</a></li>
                        {% else %}
                            <li><a class="pagination-link" aria-label="Goto page 1" href="?page={{ page }}">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </nav>
            {% endif %}
            </div>
            <div class="Sidebar">
                <div class="sidebar_card">
                {% if request.session.is_login %}
                     <div class="user_card">
                        <img src="{{ user.avatars.url }}" class="round_icon"  alt="">
                        <h1 class="user_meta nick"><a href="{% url 'user_index' user.id %}">{{ user.nick }}</a></h1>
                        <p class="introduction">个性签名：{{ user.introduction }}</p>
                        <div class="user_meta logout"><a href="{% url 'logout' %}">退出登录</a></div>
                     </div>
                {% endif %}
                {% for sidebar in Sidebar %}
                    {% if sidebar.status == 1 %}
                        <div class="{{ sidebar.class_name }}">
                        <h1>{{ sidebar.title }}</h1>
                        {% load re_url %}
                        <p>{% autoescape off  %}{{ sidebar.content | cut:request.path }}{% endautoescape %}</p>
                        </div>
                    {% endif %}
                {% endfor %}
                 <div class="Related Links">
                 <h1>友情链接</h1>
                     {% for foo in links %}
                         <p><a href="{{ foo.href }}" target="_blank">{{ foo.title }}</a></p>
                     {% endfor %}
                </div>
                </div>
            </div>
        </div>
        {# 页脚 #}
        <div class="Footer">
            <hr>
            <div class="lice text-tint">
                Copyright ©2019 风语
            </div>
            <div class="lice">
                <span><a href="{% url 'index' %}">Fy's Blog&nbsp;|&nbsp;</a></span>
                <span><a href="{% url 'sitemap' %}">sitemap&nbsp;|&nbsp;</a></span>
                <span><a href="{% url 'rss' %}">rss</a></span>

            </div>
        </div>
    </div>




</body>
</html>

FyBlog/FyBlog/FyBlog/theme/bootstrap/templates/blog/base_forget_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/bulma.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/user.css' %}" rel="stylesheet">
    <link href="{% static 'css/documentations.css' %}" rel="stylesheet">

</head>
<body style="background-color: #ffffff">
<div class="tile is-ancestor">
    <div class="tile is-parent is-vertical is-2">
        <div class="tile is-child notification" style="background: #0a0a0a;color: #ffffff;">
             <strong>Fy's Blog</strong>
        </div>
        <div class="tile is-child notification" style="border-radius: 4px;'">
            <aside class="menu">
                <p class="menu-label">General</p>
                    <ul class="menu-list">
                        <li><a href="{% url 'index' %}">返回主页</a></li>
                    </ul>
                <p class="menu-label">login</p>
                    <ul class="menu-list">
                        <li><a href="{% url 'login' %}">login in</a></li>
                        <li><a href="{% url 'register' %}">register</a></li>
                    </ul>
                <p class="menu-label">category</p>
                <ul class="menu-list">
                    {% for categroy in categorys %}
                        <li><a href="{% url 'category' categroy.id %}">{{ categroy.name }}</a></li>
                    {% endfor %}
                </ul>
                <p class="menu-label">tag</p>
                <ul class="menu-list">
                    {% for tag in tags %}
                        <li><a href="{% url 'tag' %}?tag={{ tag.id }}">{{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </aside>
        </div>
    </div>
    <div class="tile is-parent is-vertical">
        <div class="tile is-child">
            <div class="tile is-child notification" style="padding: 1.5em;">
                <ul class="steps has-content-centered">
                    <li class="steps-segment {% block first_step %}{% endblock %}">
                        <span class="steps-marker"></span>
                        <div class="steps-content">
                            <p class="is-size-4">第一步</p>
                            <p>输入你的邮箱地址</p>
                        </div>
                    </li>
                    <li class="steps-segment {% block second_step %}{% endblock %}">
                        <span class="steps-marker"></span>
                        <div class="steps-content">
                            <p class="is-size-4">第二步</p>
                            <p>选择修改密码的方式</p>
                        </div>
                    </li>
                    <li class="steps-segment {% block third_step %}{% endblock %}">
                        <span class="steps-marker"></span>
                        <div class="steps-content">
                            <p class="is-size-4">第三步</p>
                            <p>输入验证答案修改密码</p>
                        </div>
                    </li>
                    <li class="steps-segment {% block fourth_step %}{% endblock %}">
                        <span class="steps-marker"></span>
                        <div class="steps-content">
                            <p class="is-size-4">第四步</p>
                            <p>完成！</p>
                        </div>
                    </li>
                </ul>
            </div>
            <br>
             <div class="tile is-child notification" style="padding: 1.5cm 1.5cm 5cm 3cm;">
                {% block content %}{% endblock %}
            </div>
        </div>


    </div>
</div>


</body>
</html>

FyBlog/FyBlog/FyBlog/theme/bootstrap/templates/blog/complate_page.html
{% extends 'blog/base_forget_password.html' %}
{% block fourth_step %}is-active{% endblock %}
{% block content %}
<div id="content_forget">
    <article class="message is-success">
        <div class="message-body">
            <div class="level">
               <div class="level-left">
                    <div class="level-item">
                        <i class="fa fa-envelope" style="font-size: 5em"></i>
                    </div>
                    <div class="level-item">
                        <p>修改密码成功！请<a href="{% url 'login' %}?next=/blog/index/">登录</a>你的账号</p>
                    </div>
                </div>
            </div>
        </div>
    </article>
</div>

{% endblock %}

FyBlog/FyBlog/FyBlog/theme/bootstrap/templates/blog/email.html
{% extends 'blog/base_forget_password.html' %}
{% block first_step %}is-active{% endblock %}
{% block content %}
    <form action="/login/forget_password/choose/" id="content_forget" method="POST">
        {% csrf_token %}
        {% for foo in form %}
             <p>{{ foo.label }}</p>
                {{ foo }}
            {% if foo.errors %}
                <div class="error_message">
                    {{ foo.errors }}
                </div>
            {% endif %}
        {% endfor %}


        <input class="button is-rounded" value="提交" type="submit" id="form_submit">
    </form>
{% endblock %}

FyBlog/FyBlog/FyBlog/theme/bootstrap/templates/blog/login.html
{% extends 'blog/form.html' %}
{% block title %}
登陆你的账号
{% endblock %}
{% load static %}
{% block head_title %}
<h1>登陆你的账号吧!</h1>
{% endblock %}
{% block post %}/login/?next={{ next }}{% endblock %}
{% block form %}
{% csrf_token %}
    <input name="next" type="hidden" value="{{ next }}">
{% for foo in form %}
    {% if foo.label == "记住我" %}
        <p>{{ foo }}&nbsp{{ foo.label }}</p>
    {% else %}
        <p>{{ foo.label }}</p>
        {{ foo }}
    {% endif %}
    {% if foo.errors %}
        <div class="error_message">
            {{ foo.errors }}
        </div>
    {% endif %}
{% endfor %}




{% endblock %}
{% block type %}登录{% endblock %}
{% block other %}<a class="forget_password" href="{% url 'forget_password' %}">忘记密码？</a>{% endblock %}
{#<script type="text/javascript">#}
{#    var post = $("#form_submit");#}
{#    $(document).ready(function () {#}
{#        post.click(function () {#}
{#            $.ajax({#}
{#                type:"post",#}
{#                url:"/login/",#}
{#            data:{#}
{#                "username":$("#id_Email").val(),#}
{#                "password":$("#id_password").val(),#}
{#                "next":$("#next").val()#}
{#            },#}
{#            dataType:"json",#}
{#            async:false,#}
{#            })#}
{#        })#}
{#    })#}
{#</script>#}